Pod::Spec.new do |s|
  s.name                   = 'AgentSDK'
  s.version                = ENV['ARIA_VERSION'] || '0.1.0'
  s.summary                = 'Swift binding for the Aria agent platform (libagent_sdk FFI).'
  s.description            = 'High-level Swift API over the native libagent_sdk cdylib, ' \
                             'generated by cargo run -p agent-ffigen.'
  s.homepage               = 'https://github.com/ariacompute/agent'
  s.license                = { :type => 'MIT' }
  s.author                 = { 'AriaCompute' => 'https://github.com/ariacompute' }
  s.source                 = { :git => 'https://github.com/ariacompute/agent.git', :tag => "v#{s.version}" }

  s.swift_version          = '5.9'
  s.ios.deployment_target  = '13.0'
  s.osx.deployment_target  = '11.0'

  # High-level Swift wrapper + the low-level FFI modulemap/header.
  s.source_files           = 'Sources/AgentSDK/**/*', 'Sources/agent_sdkFFI/agent_sdkFFI.h', 'Sources/agent_sdkFFI/agent_sdkFFI.modulemap'
  s.preserve_paths         = 'Sources/agent_sdkFFI/agent_sdkFFI.modulemap', 'Sources/agent_sdkFFI/agent_sdkFFI.h'

  # The native lib is built separately (cargo build -p agent-sdk) and dropped in
  # next to this podspec before `pod trunk push`.
  s.vendored_libraries     = 'Sources/agent_sdkFFI/libagent_sdk.a'
  s.xcconfig               = {
    'OTHER_LDFLAGS' => '-L${PODS_ROOT}/AgentSDK/Sources/agent_sdkFFI'
  }
end
