Pod::Spec.new do |s|
  s.name                   = 'AriaAgent'
  s.version                = ENV['ARIA_VERSION'] || '0.1.0'
  s.summary                = 'Swift binding for the Aria agent platform (libaria-agent_ffi FFI).'
  s.description            = 'High-level Swift API over the native libaria-agent_ffi cdylib, ' \
                             'generated by cargo run -p aria-agent-ffigen.'
  s.homepage               = 'https://github.com/ariacompute/agent'
  s.license                = { :type => 'MIT' }
  s.author                 = { 'AriaCompute' => 'https://github.com/ariacompute' }
  s.source                 = { :git => 'https://github.com/ariacompute/agent.git', :tag => "v#{s.version}" }

  s.swift_version          = '5.9'
  s.ios.deployment_target  = '13.0'
  s.osx.deployment_target  = '11.0'

  # High-level Swift wrapper + the low-level FFI modulemap/header.
  s.source_files           = 'Sources/AriaAgent/**/*', 'Sources/aria_agent_ffi/aria_agent_ffi.h', 'Sources/aria_agent_ffi/aria_agent_ffi.modulemap'
  s.preserve_paths         = 'Sources/aria_agent_ffi/aria_agent_ffi.modulemap', 'Sources/aria_agent_ffi/aria_agent_ffi.h'

  # The native lib is built separately (cargo build -p ariacompute-agent) and dropped in
  # next to this podspec before `pod trunk push`.
  s.vendored_libraries     = 'Sources/aria_agent_ffi/libaria-agent_ffi.a'
  s.xcconfig               = {
    'OTHER_LDFLAGS' => '-L${PODS_ROOT}/AriaAgent/Sources/aria_agent_ffi'
  }
end
