// swift-tools-version:5.9
import PackageDescription

// AgentSDK Swift package.
//
// The high-level API lives in `Sources/AgentSDK/agent_sdk.swift` (generated by
// `cargo run -p agent-ffigen`). The low-level FFI modulemap + header are in
// `Sources/agent_sdkFFI/` and link the native `libagent_sdk` cdylib.
//
// Build the native lib first:  cargo build -p agent-sdk
// then either copy `libagent_sdk.dylib`/`libagent_sdk.so` next to the app, or
// point the linker at it.

let package = Package(
    name: "AgentSDK",
    products: [
        .library(name: "AgentSDK", targets: ["AgentSDK"]),
    ],
    targets: [
        .systemLibrary(name: "agent_sdkFFI"),
        .target(
            name: "AgentSDK",
            dependencies: ["agent_sdkFFI"],
            path: "Sources/AgentSDK"
        ),
    ]
)
