// swift-tools-version:5.9
import PackageDescription

// AriaComputeAgent Swift package.
//
// The high-level API lives in `Sources/AriaComputeAgent/aria_agent_ffi.swift` (generated by
// `cargo run -p aria-agent-ffigen`). The low-level FFI modulemap + header are in
// `Sources/aria_agent_ffi/` and link the native `libaria-agent_ffi` cdylib.
//
// Build the native lib first:  cargo build -p ariacompute-agent
// then either copy `libaria-agent_ffi.dylib`/`libaria-agent_ffi.so` next to the app, or
// point the linker at it.

let package = Package(
    name: "AriaComputeAgent",
    products: [
        .library(name: "AriaComputeAgent", targets: ["AriaComputeAgent"]),
    ],
    targets: [
        .systemLibrary(name: "aria_agent_ffi"),
        .target(
            name: "AriaComputeAgent",
            dependencies: ["aria_agent_ffi"],
            path: "Sources/AriaComputeAgent"
        ),
    ]
)
